name: Pull request tests

permissions:
  contents: read

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  basic-checks:
    uses: ./.github/workflows/basic.yml

  platform-tests:
    needs: basic-checks
    uses: ./.github/workflows/platforms.yml
    timeout-minutes: 85 # minutes, max + 3*std over the last 20,000 successful runs

  code-coverage:
    needs: basic-checks
    uses: ./.github/workflows/code-coverage.yml
    secrets: inherit

  scorecard:
    needs: basic-checks
    uses: ./.github/workflows/scorecard.yml
    secrets: inherit
    permissions:
      id-token: write
      security-events: write
